const fs = require('fs');
const path = require('path');

const content = [
"import React from 'react';",
"import {",
"\tActivityIndicator,",
"\tAnimated,",
"\tEasing,",
"\tImage,",
"\tPlatform,",
"\tStyleSheet,",
"\tText,",
"\tView,",
"} from 'react-native';",
"import MapView, {",
"\tMarker,",
"\tPolyline,",
"\tPROVIDER_GOOGLE,",
"\tPROVIDER_DEFAULT,",
"} from 'react-native-maps';",
"import { Ionicons } from '@expo/vector-icons';",
"import { useTheme } from '../../../hooks/useTheme';",
"import { withAlpha } from '../../../utils/color';",
"import { RiderLocation } from '../../../types/groupChat';",
"",
"const RIDER_MARKER_ICON = { uri: 'https://img.icons8.com/ios-filled/100/1A73E8/navigation.png' };",
"const DESTINATION_MARKER_ICON = { uri: 'https://img.icons8.com/ios-filled/100/D93025/marker.png' };",
"const SOURCE_MARKER_ICON = { uri: 'https://img.icons8.com/ios-filled/100/32A852/marker.png' };",
"",
"const DEFAULT_REGION = { latitude: 11.0017, longitude: 76.9619, latitudeDelta: 0.08, longitudeDelta: 0.08 };",
"",
"type LatLng = { latitude: number; longitude: number };",
"",
"// Google Encoded Polyline Algorithm",
"// https://developers.google.com/maps/documentation/utilities/polylinealgorithm",
"function decodePolyline(encoded: string): LatLng[] {",
"\tconst points: LatLng[] = [];",
"\tlet index = 0;",
"\tconst len = encoded.length;",
"\tlet lat = 0;",
"\tlet lng = 0;",
"\twhile (index < len) {",
"\t\tlet shift = 0;",
"\t\tlet result = 0;",
"\t\tlet byte: number;",
"\t\tdo {",
"\t\t\tbyte = encoded.charCodeAt(index++) - 63;",
"\t\t\tresult |= (byte & 0x1f) << shift;",
"\t\t\tshift += 5;",
"\t\t} while (byte >= 0x20);",
"\t\tconst dLat = result & 1 ? ~(result >> 1) : result >> 1;",
"\t\tlat += dLat;",
"\t\tshift = 0;",
"\t\tresult = 0;",
"\t\tdo {",
"\t\t\tbyte = encoded.charCodeAt(index++) - 63;",
"\t\t\tresult |= (byte & 0x1f) << shift;",
"\t\t\tshift += 5;",
"\t\t} while (byte >= 0x20);",
"\t\tconst dLng = result & 1 ? ~(result >> 1) : result >> 1;",
"\t\tlng += dLng;",
"\t\tpoints.push({ latitude: lat / 1e5, longitude: lng / 1e5 });",
"\t}",
"\treturn points;",
"}",
"",
"async function geocodePlace(label: string, apiKey: string): Promise<LatLng | null> {",
"\tif (!label || label.trim().length < 3) return null;",
"\ttry {",
"\t\tconst url = 'https://maps.googleapis.com/maps/api/geocode/json?address=' +",
"\t\t\tencodeURIComponent(label.trim()) + '&key=' + encodeURIComponent(apiKey);",
"\t\tconst res = await fetch(url);",
"\t\tconst data = (await res.json()) as {",
"\t\t\tstatus: string;",
"\t\t\tresults?: { geometry?: { location?: { lat?: number; lng?: number } } }[];",
"\t\t};",
"\t\tif (data.status !== 'OK' || !data.results?.length) return null;",
"\t\tconst loc = data.results[0]?.geometry?.location;",
"\t\tif (typeof loc?.lat !== 'number' || typeof loc?.lng !== 'number') return null;",
"\t\treturn { latitude: loc.lat, longitude: loc.lng };",
"\t} catch { return null; }",
"}",
"",
"async function fetchRoutePolyline(origin: LatLng, destination: LatLng, apiKey: string): Promise<LatLng[]> {",
"\ttry {",
"\t\tconst url =",
"\t\t\t'https://maps.googleapis.com/maps/api/directions/json?' +",
"\t\t\t'origin=' + origin.latitude + ',' + origin.longitude +",
"\t\t\t'&destination=' + destination.latitude + ',' + destination.longitude +",
"\t\t\t'&mode=driving&key=' + encodeURIComponent(apiKey);",
"\t\tconst res = await fetch(url);",
"\t\tconst data = (await res.json()) as {",
"\t\t\tstatus: string;",
"\t\t\troutes?: { overview_polyline?: { points?: string } }[];",
"\t\t};",
"\t\tif (data.status !== 'OK' || !data.routes?.length) return [];",
"\t\tconst encoded = data.routes[0]?.overview_polyline?.points;",
"\t\tif (!encoded) return [];",
"\t\treturn decodePolyline(encoded);",
"\t} catch { return []; }",
"}",
"",
"const regionForPoints = (points: LatLng[]) => {",
"\tif (points.length === 0) return DEFAULT_REGION;",
"\tconst lats = points.map(p => p.latitude);",
"\tconst lngs = points.map(p => p.longitude);",
"\tconst minLat = Math.min(...lats), maxLat = Math.max(...lats);",
"\tconst minLng = Math.min(...lngs), maxLng = Math.max(...lngs);",
"\treturn {",
"\t\tlatitude: (minLat + maxLat) / 2,",
"\t\tlongitude: (minLng + maxLng) / 2,",
"\t\tlatitudeDelta: Math.max(maxLat - minLat, 0.012) * 2.4,",
"\t\tlongitudeDelta: Math.max(maxLng - minLng, 0.012) * 2.4,",
"\t};",
"};",
"",
"interface LiveMapSectionProps {",
"\triders: RiderLocation[];",
"\tleaderRiderId?: string | null;",
"\trecenterSignal?: number;",
"\tisRideEnded?: boolean;",
"\t/** false → pre-ride: road route preview; true → live rider tracking */",
"\trideStarted?: boolean;",
"\tsourceLabel?: string;",
"\tdestinationLabel?: string;",
"\tlastUpdatedAt?: string | null;",
"}",
"",
"interface RiderMarkerViewProps { isLeader: boolean; markerPulse: Animated.Value; }",
"",
"const RiderMarkerView = React.memo(function RiderMarkerView({ isLeader, markerPulse }: RiderMarkerViewProps) {",
"\treturn (",
"\t\t<View style={markerStyles.wrap}>",
"\t\t\t<Animated.View",
"\t\t\t\tstyle={[markerStyles.pulse, isLeader && markerStyles.leaderPulse, { transform: [{ scale: markerPulse }] }]}",
"\t\t\t/>",
"\t\t\t<Image source={RIDER_MARKER_ICON} style={markerStyles.icon} />",
"\t\t</View>",
"\t);",
"});",
"",
"const markerStyles = StyleSheet.create({",
"\twrap: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },",
"\tpulse: { position: 'absolute', bottom: 4, width: 13, height: 13, borderRadius: 999, backgroundColor: withAlpha('#1b67ff', 0.35) },",
"\tleaderPulse: { backgroundColor: withAlpha('#E83A3A', 0.38), width: 16, height: 16 },",
"\ticon: { width: 26, height: 26, resizeMode: 'contain', transform: [{ rotate: '-18deg' }] },",
"});",
"",
"export function LiveMapSection({",
"\triders,",
"\tleaderRiderId,",
"\trecenterSignal = 0,",
"\tisRideEnded = false,",
"\trideStarted = false,",
"\tsourceLabel,",
"\tdestinationLabel,",
"}: LiveMapSectionProps) {",
"\tconst { colors, metrics, typography } = useTheme();",
"\tconst mapRef = React.useRef<MapView>(null);",
"\tconst markerPulse = React.useRef(new Animated.Value(0.72)).current;",
"\tconst [sourceCoord, setSourceCoord] = React.useState<LatLng | null>(null);",
"\tconst [destCoord, setDestCoord] = React.useState<LatLng | null>(null);",
"\tconst [routePoints, setRoutePoints] = React.useState<LatLng[]>([]);",
"\tconst [loading, setLoading] = React.useState(false);",
"",
"\t// Step 1: geocode source + destination labels",
"\tReact.useEffect(() => {",
"\t\tconst apiKey = process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY ?? '';",
"\t\tif (!apiKey) return;",
"\t\tlet cancelled = false;",
"\t\tsetLoading(true);",
"\t\tPromise.all([",
"\t\t\tsourceLabel ? geocodePlace(sourceLabel, apiKey) : Promise.resolve(null),",
"\t\t\tdestinationLabel ? geocodePlace(destinationLabel, apiKey) : Promise.resolve(null),",
"\t\t]).then(([src, dst]) => {",
"\t\t\tif (cancelled) return;",
"\t\t\tsetSourceCoord(src);",
"\t\t\tsetDestCoord(dst);",
"\t\t});",
"\t\treturn () => { cancelled = true; };",
"\t}, [sourceLabel, destinationLabel]);",
"",
"\t// Step 2: fetch actual road route via Directions API once both coords known",
"\tReact.useEffect(() => {",
"\t\tconst apiKey = process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY ?? '';",
"\t\tif (!apiKey || !sourceCoord || !destCoord) { setLoading(false); return; }",
"\t\tlet cancelled = false;",
"\t\tsetLoading(true);",
"\t\tfetchRoutePolyline(sourceCoord, destCoord, apiKey).then(pts => {",
"\t\t\tif (cancelled) return;",
"\t\t\tsetRoutePoints(pts);",
"\t\t\tsetLoading(false);",
"\t\t});",
"\t\treturn () => { cancelled = true; };",
"\t}, [sourceCoord, destCoord]);",
"",
"\tconst ridersSorted = React.useMemo(",
"\t\t() => [...riders].sort((a, b) =>",
"\t\t\ta.updatedAt === b.updatedAt ? a.riderId.localeCompare(b.riderId) : a.updatedAt.localeCompare(b.updatedAt)",
"\t\t),",
"\t\t[riders],",
"\t);",
"",
"\tconst leaderRider = React.useMemo(",
"\t\t() => ridersSorted.find(r => r.riderId === leaderRiderId) ?? ridersSorted[0] ?? null,",
"\t\t[leaderRiderId, ridersSorted],",
"\t);",
"",
"\tReact.useEffect(() => {",
"\t\tconst anim = Animated.loop(Animated.sequence([",
"\t\t\tAnimated.timing(markerPulse, { toValue: 1, duration: 700, easing: Easing.out(Easing.quad), useNativeDriver: true }),",
"\t\t\tAnimated.timing(markerPulse, { toValue: 0.72, duration: 700, easing: Easing.in(Easing.quad), useNativeDriver: true }),",
"\t\t]));",
"\t\tanim.start();",
"\t\treturn () => anim.stop();",
"\t}, [markerPulse]);",
"",
"\t// Recenter camera on leader when recenterSignal fires",
"\tReact.useEffect(() => {",
"\t\tif (!mapRef.current || !rideStarted || !leaderRider) return;",
"\t\tmapRef.current.animateToRegion({",
"\t\t\tlatitude: leaderRider.latitude, longitude: leaderRider.longitude,",
"\t\t\tlatitudeDelta: 0.025, longitudeDelta: 0.025,",
"\t\t}, 500);",
"\t\t// eslint-disable-next-line react-hooks/exhaustive-deps",
"\t}, [recenterSignal]);",
"",
"\t// Fit camera to road route in preview mode",
"\tReact.useEffect(() => {",
"\t\tif (!mapRef.current || rideStarted || routePoints.length === 0) return;",
"\t\tmapRef.current.animateToRegion(regionForPoints(routePoints), 700);",
"\t}, [rideStarted, routePoints]);",
"",
"\t// Fit camera to all riders + destination in live mode",
"\tReact.useEffect(() => {",
"\t\tif (!mapRef.current || !rideStarted || ridersSorted.length === 0) return;",
"\t\tconst pts = ridersSorted.map(r => ({ latitude: r.latitude, longitude: r.longitude }));",
"\t\tif (destCoord) pts.push(destCoord);",
"\t\tmapRef.current.animateToRegion(regionForPoints(pts), 600);",
"\t}, [rideStarted, ridersSorted, destCoord]);",
"",
"\t// Live mode: simple connecting line from each rider to destination",
"\tconst livePolylineCoords = React.useMemo<LatLng[]>(() => {",
"\t\tif (!rideStarted || ridersSorted.length === 0) return [];",
"\t\tconst pts = ridersSorted.map(r => ({ latitude: r.latitude, longitude: r.longitude }));",
"\t\tif (destCoord) pts.push(destCoord);",
"\t\treturn pts;",
"\t}, [rideStarted, ridersSorted, destCoord]);",
"",
"\tconst styles = React.useMemo(() => StyleSheet.create({",
"\t\twrap: { marginHorizontal: metrics.md, borderRadius: 18, overflow: 'hidden', height: 320, borderWidth: 1, borderColor: '#EAEAEA', backgroundColor: '#E9EEEA' },",
"\t\tmap: { ...StyleSheet.absoluteFillObject },",
"\t\trideChip: {",
"\t\t\tposition: 'absolute', top: metrics.sm, left: metrics.sm, borderRadius: 999,",
"\t\t\tpaddingHorizontal: metrics.sm, paddingVertical: metrics.xs,",
"\t\t\tbackgroundColor: withAlpha(isRideEnded ? colors.error : rideStarted ? '#32A852' : '#1B67FF', 0.18),",
"\t\t\tborderWidth: 1, borderColor: withAlpha(isRideEnded ? colors.error : rideStarted ? '#32A852' : '#1B67FF', 0.45),",
"\t\t},",
"\t\trideChipText: { color: isRideEnded ? colors.error : rideStarted ? '#2B8A3E' : '#1553B6', fontSize: typography.sizes.xs, fontWeight: '800', letterSpacing: 0.3 },",
"\t\tspeedChip: { position: 'absolute', left: metrics.sm, bottom: metrics.sm, width: 64, height: 64, borderRadius: 32, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#EFEFEF' },",
"\t\tspeedValue: { color: colors.textPrimary, fontSize: typography.sizes['2xl'], fontWeight: '700', lineHeight: typography.sizes['2xl'] },",
"\t\tspeedUnit: { color: colors.textSecondary, fontSize: typography.sizes.xs, fontWeight: '600' },",
"\t\temptyWrap: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', gap: metrics.xs, paddingHorizontal: metrics.lg, backgroundColor: '#E9EEEA' },",
"\t\temptyText: { color: colors.textSecondary, fontSize: typography.sizes.sm, textAlign: 'center' },",
"\t\tloadingOverlay: { position: 'absolute', top: metrics.sm, right: metrics.sm, backgroundColor: withAlpha('#FFFFFF', 0.85), borderRadius: 99, padding: 6 },",
"\t\tpinLabel: { position: 'absolute', backgroundColor: '#FFFFFF', borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2, top: -22, alignSelf: 'center', shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 4, shadowOffset: { width: 0, height: 1 }, elevation: 2 },",
"\t\tpinLabelText: { fontSize: 10, fontWeight: '700', color: '#111827', maxWidth: 110 },",
"\t}), [colors, isRideEnded, rideStarted, metrics, typography]);",
"",
"\tconst chipLabel = isRideEnded ? 'RIDE ENDED' : rideStarted ? 'RIDE LIVE' : 'ROUTE PREVIEW';",
"\tconst showEmpty = rideStarted && ridersSorted.length === 0;",
"\tconst showSpeedChip = rideStarted || isRideEnded;",
"",
"\treturn (",
"\t\t<View style={styles.wrap}>",
"\t\t\t<MapView",
"\t\t\t\tref={mapRef}",
"\t\t\t\tstyle={styles.map}",
"\t\t\t\tprovider={Platform.OS === 'android' ? PROVIDER_GOOGLE : PROVIDER_DEFAULT}",
"\t\t\t\tinitialRegion={DEFAULT_REGION}",
"\t\t\t\tshowsUserLocation={false}",
"\t\t\t\tshowsMyLocationButton={false}",
"\t\t\t\tshowsCompass={false}",
"\t\t\t\tshowsScale={false}",
"\t\t\t\ttoolbarEnabled={false}",
"\t\t\t\tmoveOnMarkerPress={false}",
"\t\t\t\trotateEnabled={false}",
"\t\t\t\tmapType='standard'",
"\t\t\t>",
"\t\t\t\t{/* PRE-RIDE: road route polyline decoded from Directions API */}",
"\t\t\t\t{!rideStarted && routePoints.length >= 2 && (",
"\t\t\t\t\t<>",
"\t\t\t\t\t\t<Polyline coordinates={routePoints} strokeColor={withAlpha('#1557D3', 0.28)} strokeWidth={9} lineJoin='round' lineCap='round' />",
"\t\t\t\t\t\t<Polyline coordinates={routePoints} strokeColor='#1B67FF' strokeWidth={6} lineJoin='round' lineCap='round' />",
"\t\t\t\t\t</>",
"\t\t\t\t)}",
"",
"\t\t\t\t{/* LIVE: connecting line from riders toward destination */}",
"\t\t\t\t{rideStarted && livePolylineCoords.length >= 2 && (",
"\t\t\t\t\t<>",
"\t\t\t\t\t\t<Polyline coordinates={livePolylineCoords} strokeColor={withAlpha('#1557D3', 0.28)} strokeWidth={9} lineJoin='round' lineCap='round' />",
"\t\t\t\t\t\t<Polyline coordinates={livePolylineCoords} strokeColor='#1B67FF' strokeWidth={6} lineJoin='round' lineCap='round' />",
"\t\t\t\t\t</>",
"\t\t\t\t)}",
"",
"\t\t\t\t{/* PRE-RIDE: source pin (green) */}",
"\t\t\t\t{!rideStarted && sourceCoord && (",
"\t\t\t\t\t<Marker coordinate={sourceCoord} anchor={{ x: 0.5, y: 1 }} tracksViewChanges={false}>",
"\t\t\t\t\t\t<View>",
"\t\t\t\t\t\t\t<View style={styles.pinLabel}>",
"\t\t\t\t\t\t\t\t<Text style={styles.pinLabelText} numberOfLines={1} ellipsizeMode='tail'>{sourceLabel ?? 'Start'}</Text>",
"\t\t\t\t\t\t\t</View>",
"\t\t\t\t\t\t\t<Image source={SOURCE_MARKER_ICON} style={{ width: 26, height: 26, resizeMode: 'contain' }} />",
"\t\t\t\t\t\t</View>",
"\t\t\t\t\t</Marker>",
"\t\t\t\t)}",
"",
"\t\t\t\t{/* LIVE: rider markers with pulse animation */}",
"\t\t\t\t{rideStarted && ridersSorted.map(rider => (",
"\t\t\t\t\t<Marker",
"\t\t\t\t\t\tkey={rider.riderId}",
"\t\t\t\t\t\tcoordinate={{ latitude: rider.latitude, longitude: rider.longitude }}",
"\t\t\t\t\t\ttitle={rider.name}",
"\t\t\t\t\t\tanchor={{ x: 0.5, y: 0.9 }}",
"\t\t\t\t\t\ttracksViewChanges={false}",
"\t\t\t\t\t>",
"\t\t\t\t\t\t<RiderMarkerView isLeader={rider.riderId === leaderRider?.riderId} markerPulse={markerPulse} />",
"\t\t\t\t\t</Marker>",
"\t\t\t\t))}",
"",
"\t\t\t\t{/* Destination pin — always shown once geocoded, never moves */}",
"\t\t\t\t{destCoord && (",
"\t\t\t\t\t<Marker coordinate={destCoord} anchor={{ x: 0.5, y: 1 }} tracksViewChanges={false}>",
"\t\t\t\t\t\t<View>",
"\t\t\t\t\t\t\t<View style={styles.pinLabel}>",
"\t\t\t\t\t\t\t\t<Text style={styles.pinLabelText} numberOfLines={1} ellipsizeMode='tail'>{destinationLabel ?? 'Destination'}</Text>",
"\t\t\t\t\t\t\t</View>",
"\t\t\t\t\t\t\t<Image source={DESTINATION_MARKER_ICON} style={{ width: 26, height: 26, resizeMode: 'contain' }} />",
"\t\t\t\t\t\t</View>",
"\t\t\t\t\t</Marker>",
"\t\t\t\t)}",
"\t\t\t</MapView>",
"",
"\t\t\t{showEmpty && (",
"\t\t\t\t<View style={styles.emptyWrap}>",
"\t\t\t\t\t<Ionicons color={withAlpha(colors.textPrimary, 0.6)} name='map-outline' size={34} />",
"\t\t\t\t\t<Text style={styles.emptyText}>No rider locations yet. Tracking will appear here.</Text>",
"\t\t\t\t</View>",
"\t\t\t)}",
"\t\t\t{loading && (",
"\t\t\t\t<View style={styles.loadingOverlay}>",
"\t\t\t\t\t<ActivityIndicator size='small' color={colors.primary} />",
"\t\t\t\t</View>",
"\t\t\t)}",
"\t\t\t<View style={styles.rideChip}>",
"\t\t\t\t<Text style={styles.rideChipText}>{chipLabel}</Text>",
"\t\t\t</View>",
"\t\t\t{showSpeedChip && (",
"\t\t\t\t<View style={styles.speedChip}>",
"\t\t\t\t\t<Text style={styles.speedValue}>0</Text>",
"\t\t\t\t\t<Text style={styles.speedUnit}>km/h</Text>",
"\t\t\t\t</View>",
"\t\t\t)}",
"\t\t</View>",
"\t);",
"}",
].join('\n');

fs.writeFileSync(path.join(__dirname, 'src/components/chat/group/LiveMapSection.tsx'), content, 'utf8');
console.log('Written successfully. Lines:', content.split('\n').length);
